# Generated by Django 4.1.1 on 2022-10-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_order_alter_product_rating_shippingaddress_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
