# Generated by Django 4.1.1 on 2022-10-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
    ]
